Connect 4 Game
bfwetmore/connectfour pull request #1
Opened 2022-02-15 03:01 UTC by bfwetmore

# Connect 4 Game
 
Two player game where objective is to drop tokens into grid style board. First player to place 4 tokens in a row, horizontally, vertically or diagonally wins.

### Game.js and App.js file

- Add full game file. Contains Game Class which carries most of the games logic.
- Add full App file. Contains interaction with the DOM to launch the game.
- Add supporting HTML and CSS files.

### Board.js and Space.js

- Add Board.js file, which constructs game board, and populates it with space objects from the following file.
- Add Space.js file, contains method to draw spaces on the board and creates the space class.

### Player.js and Token.js

- Add Player.js file which holds the Player Class and contains most token associated methods.
- Add Token.js file which holds the Token Class. Also makes changes to the DOM for token movement and effects from user inputs.

2022-02-17 15:41 UTC, do-work requested changes

2022-02-17 15:41 UTC, do-work commented on index.html
> +        -->
Id remove a comment like this.
Your just repeating the id and giving me info thats obvious or I dont need.

2022-02-17 15:41 UTC, do-work commented on index.html
> +-->
I think this is overkill but I also think its kind of helpful.

2022-02-17 15:41 UTC, do-work commented on index.html
> +        -->
This one feels unnecessary though..

2022-02-17 15:41 UTC, do-work commented on index.html
> +        -->
Id skip this one.

2022-02-17 15:41 UTC, do-work commented on index.html
> +                -->
Id skip.

2022-02-17 15:41 UTC, do-work commented on index.html
> +        -->
If you were going to keep this I would make it a single line comment and remove the class name prefix. Its implied by being right above it.

2022-02-17 15:41 UTC, do-work commented on index.html
> +-->
I like this one. Your not saying what it does - your saying why. This is a near perfect comment.
Single line and remove the class prefix and I think its perfect.

2022-02-17 15:41 UTC, do-work commented on index.html
> +
Why 2 blank lines?

2022-02-17 15:41 UTC, do-work commented on index.html
> +
Why 3 blank lines?

2022-02-17 15:41 UTC, do-work commented on js/Board.js
> +        this.spaces = this.createSpaces();
This is what is often called a "side effect".
What that means is that when you 'get' (AKA instantiate) an instance of your Board class AND that process (via the constructor) does _something_. 

In some instances it will feel like you need to do this and that might be true. Generally you want to move actual logic out of the constructor and put it somewhere else. You want to be able to get an instance of the class without DOING anything else. You dont want to have to look into the class constructor to see IF it might do something..

2022-02-17 15:41 UTC, do-work commented on js/Board.js
> +                column.push(space);
Id inline this..
I dont think you get any more context or info by setting the var name here. You know based on the final return that your getting multiple spaces so its implied to me that your pushing Space into an array.

Double check your return docblock on line 10 - you said Array but it should say an Array OF Spaces. Double check the convention for that,

2022-02-17 15:41 UTC, do-work commented on js/Board.js
> +    drawHTMLBoard() {
Needs a docBlock.

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +        this.board = new Board();
We want to pass this instance of Board to the constructor as an argument.
Thats what we call dependency injection (DI for short).

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +        this.players = this.createPlayers();
This is another side effect.

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +    get activePlayer() {
Needs docBlock.

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +            new Player(prompt("Please enter Player 2 Name"), 2, '#e59a13')];
Id like to see you pass the player names as arguments to this method.
This gives us flexibility to GET names from different means. What I mean is that your using a prompt right now. What if we want to get it from an external API or from a database?

Right now the way we get the names is highly 'coupled' with where we create the players. We want to keep these two separate.

Im assuming the `#e15258` is a color? Id like to see these colors defined as a const with a name for what it is.

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +
Blank line.

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +     * @param e - Keydown event object
Double check syntax on this. 
The goal of the docBlock parameter is to let us know what type the argument is since JS is dynamically typed we want to know what it should be. Like you notated that it is an event object, there should be a syntax for saying - "e IS an event object". There are more nuances to discuss about what to type it at. We will have to talk about it.

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +        if (targetSpace !== null) {
Im a little confused on this logic.

At a quick glance it seems to me that you can just return on line 59?
Then remove the conditional on line 63?

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +            game.ready = false;
Was this what you were mentioning about weird behavior with `this`?

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +            });
Arrow syntax?
IIRC arrow syntax resolves some weird issues with this. Maybe that was the issue?

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +        for (let x = 0; x < this.board.columns; x++) {
Im assuming you have yet to push those other changes here?

2022-02-17 15:41 UTC, do-work commented on js/Game.js
> +        console.log(this.checkForWin(target));
Do you need this console.log ?
Console.log is weird and used everywhere but its kind of anti pattern.
Traditional logging has levels and we can set the level of logging we want to output based on the development environment. For example in dev we might output ALL logging but in production we only want a small amount of logging.
Console.log outputs no matter what and is not able to be toggled. For that reason we usually want to avoid it BUT you will see it used all over the place anyway....

2022-02-17 15:41 UTC, do-work commented on js/Player.js
> +
Extra space.

2022-02-17 15:41 UTC, do-work commented on js/Player.js
> +    get unusedTokens() {
DocBlock.
This method name seems weird. Should it be getUnusedTokens?

2022-02-17 15:41 UTC, do-work commented on js/Player.js
> +        this.tokens = this.createTokens(21);
Side effect.

2022-02-17 15:41 UTC, do-work commented on js/Player.js
> +            tokens.push(token);
Inline.

2022-02-17 15:41 UTC, do-work commented on js/Player.js
> +
Extra space.

2022-02-17 15:41 UTC, do-work commented on js/Space.js
> +        document.getElementById("mask").appendChild(svgSpace);
I think I would split up drawing the SVG vs applying it.

2022-02-17 15:41 UTC, do-work commented on js/Token.js
> +            this.htmlTokenElement.style.left = this.offsetLeft - 76;
Where does 76 come from?

2022-02-17 21:24 UTC, bfwetmore commented on index.html
> +        -->
Done.

2022-02-17 21:24 UTC, bfwetmore commented on index.html
> +-->
Kept.

2022-02-17 21:24 UTC, bfwetmore commented on index.html
> +        -->
Removed.

2022-02-17 21:24 UTC, bfwetmore commented on index.html
> +        -->
Removed.

2022-02-17 21:24 UTC, bfwetmore commented on index.html
> +                -->
Removed.

2022-02-17 21:24 UTC, bfwetmore commented on index.html
> +        -->
I think its self explanatory, removed.

2022-02-17 21:26 UTC, bfwetmore commented on index.html
> +-->
Removed prefix.

2022-02-17 21:26 UTC, bfwetmore commented on index.html
> +
Changed to single line.

2022-02-17 21:26 UTC, bfwetmore commented on index.html
> +
Changed to single line.

2022-02-17 21:30 UTC, bfwetmore commented on js/Board.js
> +    drawHTMLBoard() {
Done

2022-02-17 21:43 UTC, bfwetmore commented on js/Board.js
> +                column.push(space);
Inlined space.  Not sure what you mean on the docblock. It says array in the curly brackets, followed with `An array of space objects. ` According to Adobe's notes on Documentation, it seems to me the convention is correct. https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-javascript.html

2022-02-17 22:18 UTC, bfwetmore commented on js/Game.js
> +        this.players = this.createPlayers();
Done.

2022-02-17 22:19 UTC, bfwetmore commented on js/Game.js
> +        this.board = new Board();
Done

2022-02-17 22:34 UTC, bfwetmore commented on js/Board.js
> +        this.spaces = this.createSpaces();
I gave it a shot, let me know what you think. Tested app, everything works as it should.

2022-02-17 22:44 UTC, bfwetmore commented on js/Game.js
> +            new Player(prompt("Please enter Player 2 Name"), 2, '#e59a13')];
Done, let me know what you think.

2022-02-17 22:44 UTC, bfwetmore commented on js/Game.js
> +    get activePlayer() {
Done.

2022-02-17 22:45 UTC, bfwetmore commented on js/Game.js
> +
Fixed.

2022-02-17 22:47 UTC, bfwetmore commented on js/Game.js
> +        console.log(this.checkForWin(target));
No that console.log was for testing purposes, weird its not in my current code. I must have removed it after I pushed.

2022-02-17 22:53 UTC, bfwetmore commented on js/Token.js
> +            this.htmlTokenElement.style.left = this.offsetLeft - 76;
76 is the Pixel size of the CSS drawing of the token.

2022-02-17 23:19 UTC, bfwetmore commented on js/Token.js
> +            this.htmlTokenElement.style.left = this.offsetLeft - 76;
Made parameters to accept an argument that comes directly from the Space Class diameter object.

2022-02-17 23:20 UTC, bfwetmore commented on js/Player.js
> +
Removed.

2022-02-17 23:21 UTC, bfwetmore commented on js/Player.js
> +            tokens.push(token);
Done.

2022-02-18 02:21 UTC, bfwetmore commented on js/Game.js
> +            game.ready = false;
Yes, in the function below that variable, because its used as a callback function, that takes it out of the "realm" per-say, of the class. Therefore it wont recognize 'this'.

2022-02-18 02:22 UTC, bfwetmore commented on js/Game.js
> +            });
Arrow syntax doesn't recognize 'this' at all regardless of its placement in the class.

2022-02-18 02:23 UTC, bfwetmore commented on js/Player.js
> +
Removed.

2022-02-18 02:25 UTC, bfwetmore commented on js/Player.js
> +    get unusedTokens() {
Since it's a dynamically changing value, the getter method is appropriate here I believe.

2022-02-18 02:26 UTC, bfwetmore commented on js/Space.js
> +        document.getElementById("mask").appendChild(svgSpace);
We will have to discuss this one, not sure I understand what you mean.

2022-02-18 03:02 UTC, bfwetmore commented on js/Game.js
> +        if (targetSpace !== null) {
This is to prevent someone from dropping a token into a full column.  If the target space is null after the loop is run, nothing happens.

2022-07-28 15:50 UTC, bfwetmore commented on js/Space.js
> +        document.getElementById("mask").appendChild(svgSpace);
Done

2022-07-28 16:30 UTC, bfwetmore commented on js/Player.js
> +        this.tokens = this.createTokens(21);
Fixed

2022-07-28 16:39 UTC, bfwetmore commented on js/Game.js
> +     * @param e - Keydown event object
Fixed to correct syntax.

2022-07-30 15:28 UTC, do-work approved these changes

2022-07-30 20:31 UTC, merged